version: '3.8'

services:
  backend:
    build:
      context: ./backend/PessoaAPI
      dockerfile: Dockerfile
    container_name: pessoa-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - pessoa-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
    container_name: pessoa-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
    depends_on:
      - backend
    networks:
      - pessoa-network
    restart: unless-stopped

networks:
  pessoa-network:
    driver: bridge

